// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;
using System.Collections.Generic;
using System.Linq;

using Microsoft.VisualStudio.TestPlatform.CommunicationUtilities;
using Microsoft.VisualStudio.TestPlatform.CommunicationUtilities.ObjectModel;
using Microsoft.VisualStudio.TestPlatform.ObjectModel;
using Microsoft.VisualStudio.TestPlatform.ObjectModel.Engine.ClientProtocol;
using Microsoft.VisualStudio.TestTools.UnitTesting;

using TestResult = Microsoft.VisualStudio.TestPlatform.ObjectModel.TestResult;

namespace Microsoft.TestPlatform.CommunicationUtilities.UnitTests.Serialization;

/// <summary>
/// Golden baseline tests that capture the exact Newtonsoft.Json serialization output.
/// After migrating to System.Text.Json, these tests verify that the new serializer
/// produces identical output.
/// </summary>
[TestClass]
[TestCategory("Serialization")]
public class SerializationGoldenTests
{
    #region Shared Test Data

    // These objects are public static readonly so they can be reused in benchmarks.
    public static readonly TestCase GoldenTestCase = new(
        "sampleTestClass.sampleTestCase",
        new Uri("executor://sampleTestExecutor"),
        "sampleTest.dll")
    {
        CodeFilePath = "/user/src/testFile.cs",
        DisplayName = "sampleTestCase",
        Id = new Guid("be78d6fc-61b0-4882-9d07-40d796fd96ce"),
        LineNumber = 999,
        Traits = { new Trait("Priority", "0"), new Trait("Category", "unit") }
    };

    public static readonly TestResult GoldenTestResult;

    public static readonly TestRunCriteriaWithTests GoldenTestRunCriteriaWithTests;

    public static readonly TestRunCriteriaWithSources GoldenTestRunCriteriaWithSources;

    static SerializationGoldenTests()
    {
        var result = new TestResult(GoldenTestCase)
        {
            Outcome = TestOutcome.Passed,
            ErrorMessage = "sampleError",
            ErrorStackTrace = "sampleStackTrace",
            DisplayName = "sampleTestResult",
            ComputerName = "sampleComputerName",
            Duration = TimeSpan.FromMilliseconds(123456),
            StartTime = new DateTimeOffset(new DateTime(2023, 1, 15, 10, 30, 0, DateTimeKind.Utc)),
            EndTime = new DateTimeOffset(new DateTime(2023, 1, 15, 10, 32, 0, DateTimeKind.Utc)),
        };

        result.Messages.Add(new TestResultMessage(TestResultMessage.StandardOutCategory, "sample stdout message"));
        result.Messages.Add(new TestResultMessage(TestResultMessage.StandardErrorCategory, "sample stderr message"));

        var attachmentSet = new AttachmentSet(new Uri("datacollector://sample"), "Sample Collector");
        attachmentSet.Attachments.Add(new UriDataAttachment(new Uri("file:///tmp/log.txt"), "Log File"));
        result.Attachments.Add(attachmentSet);

        GoldenTestResult = result;

        var executionContext = new TestExecutionContext(
            frequencyOfRunStatsChangeEvent: 10,
            runStatsChangeEventTimeout: TimeSpan.FromSeconds(60),
            inIsolation: false,
            keepAlive: true,
            isDataCollectionEnabled: false,
            areTestCaseLevelEventsRequired: false,
            hasTestRun: true,
            isDebug: false,
            testCaseFilter: null,
            filterOptions: null);

        GoldenTestRunCriteriaWithTests = new TestRunCriteriaWithTests(
            new List<TestCase> { GoldenTestCase },
            "samplePackage",
            "<RunSettings><RunConfiguration></RunConfiguration></RunSettings>",
            executionContext);

        GoldenTestRunCriteriaWithSources = new TestRunCriteriaWithSources(
            new Dictionary<string, IEnumerable<string>>
            {
                ["executor://sampleTestExecutor"] = new[] { "sampleTest.dll" }
            },
            "samplePackage",
            "<RunSettings><RunConfiguration></RunConfiguration></RunSettings>",
            executionContext);
    }

    #endregion

    #region Golden JSON Strings

    // Generated by serializing the above objects with Newtonsoft.Json via JsonDataSerializer.Instance.

    private static readonly string TestCaseV1Json =
        """
        {
          "Properties": [
            {
              "Key": {
                "Id": "TestCase.FullyQualifiedName",
                "Label": "FullyQualifiedName",
                "Category": "",
                "Description": "",
                "Attributes": 1,
                "ValueType": "System.String"
              },
              "Value": "sampleTestClass.sampleTestCase"
            },
            {
              "Key": {
                "Id": "TestCase.ExecutorUri",
                "Label": "Executor Uri",
                "Category": "",
                "Description": "",
                "Attributes": 1,
                "ValueType": "System.Uri"
              },
              "Value": "executor://sampleTestExecutor"
            },
            {
              "Key": {
                "Id": "TestCase.Source",
                "Label": "Source",
                "Category": "",
                "Description": "",
                "Attributes": 0,
                "ValueType": "System.String"
              },
              "Value": "sampleTest.dll"
            },
            {
              "Key": {
                "Id": "TestCase.CodeFilePath",
                "Label": "File Path",
                "Category": "",
                "Description": "",
                "Attributes": 0,
                "ValueType": "System.String"
              },
              "Value": "/user/src/testFile.cs"
            },
            {
              "Key": {
                "Id": "TestCase.DisplayName",
                "Label": "Name",
                "Category": "",
                "Description": "",
                "Attributes": 0,
                "ValueType": "System.String"
              },
              "Value": "sampleTestCase"
            },
            {
              "Key": {
                "Id": "TestCase.Id",
                "Label": "Id",
                "Category": "",
                "Description": "",
                "Attributes": 1,
                "ValueType": "System.Guid"
              },
              "Value": "be78d6fc-61b0-4882-9d07-40d796fd96ce"
            },
            {
              "Key": {
                "Id": "TestCase.LineNumber",
                "Label": "Line Number",
                "Category": "",
                "Description": "",
                "Attributes": 1,
                "ValueType": "System.Int32"
              },
              "Value": 999
            },
            {
              "Key": {
                "Id": "TestObject.Traits",
                "Label": "Traits",
                "Category": "",
                "Description": "",
                "Attributes": 5,
                "ValueType": "System.Collections.Generic.KeyValuePair`2[[System.String],[System.String]][]"
              },
              "Value": [
                {
                  "Key": "Priority",
                  "Value": "0"
                },
                {
                  "Key": "Category",
                  "Value": "unit"
                }
              ]
            }
          ]
        }
        """;

    private static readonly string TestCaseV2Json =
        """
        {
          "Id": "be78d6fc-61b0-4882-9d07-40d796fd96ce",
          "FullyQualifiedName": "sampleTestClass.sampleTestCase",
          "DisplayName": "sampleTestCase",
          "ExecutorUri": "executor://sampleTestExecutor",
          "Source": "sampleTest.dll",
          "CodeFilePath": "/user/src/testFile.cs",
          "LineNumber": 999,
          "Properties": [
            {
              "Key": {
                "Id": "TestObject.Traits",
                "Label": "Traits",
                "Category": "",
                "Description": "",
                "Attributes": 5,
                "ValueType": "System.Collections.Generic.KeyValuePair`2[[System.String],[System.String]][]"
              },
              "Value": [
                {
                  "Key": "Priority",
                  "Value": "0"
                },
                {
                  "Key": "Category",
                  "Value": "unit"
                }
              ]
            }
          ]
        }
        """;

    private static readonly string TestResultV1Json =
        """
        {
          "TestCase": {
            "Properties": [
              {
                "Key": {
                  "Id": "TestCase.FullyQualifiedName",
                  "Label": "FullyQualifiedName",
                  "Category": "",
                  "Description": "",
                  "Attributes": 1,
                  "ValueType": "System.String"
                },
                "Value": "sampleTestClass.sampleTestCase"
              },
              {
                "Key": {
                  "Id": "TestCase.ExecutorUri",
                  "Label": "Executor Uri",
                  "Category": "",
                  "Description": "",
                  "Attributes": 1,
                  "ValueType": "System.Uri"
                },
                "Value": "executor://sampleTestExecutor"
              },
              {
                "Key": {
                  "Id": "TestCase.Source",
                  "Label": "Source",
                  "Category": "",
                  "Description": "",
                  "Attributes": 0,
                  "ValueType": "System.String"
                },
                "Value": "sampleTest.dll"
              },
              {
                "Key": {
                  "Id": "TestCase.CodeFilePath",
                  "Label": "File Path",
                  "Category": "",
                  "Description": "",
                  "Attributes": 0,
                  "ValueType": "System.String"
                },
                "Value": "/user/src/testFile.cs"
              },
              {
                "Key": {
                  "Id": "TestCase.DisplayName",
                  "Label": "Name",
                  "Category": "",
                  "Description": "",
                  "Attributes": 0,
                  "ValueType": "System.String"
                },
                "Value": "sampleTestCase"
              },
              {
                "Key": {
                  "Id": "TestCase.Id",
                  "Label": "Id",
                  "Category": "",
                  "Description": "",
                  "Attributes": 1,
                  "ValueType": "System.Guid"
                },
                "Value": "be78d6fc-61b0-4882-9d07-40d796fd96ce"
              },
              {
                "Key": {
                  "Id": "TestCase.LineNumber",
                  "Label": "Line Number",
                  "Category": "",
                  "Description": "",
                  "Attributes": 1,
                  "ValueType": "System.Int32"
                },
                "Value": 999
              },
              {
                "Key": {
                  "Id": "TestObject.Traits",
                  "Label": "Traits",
                  "Category": "",
                  "Description": "",
                  "Attributes": 5,
                  "ValueType": "System.Collections.Generic.KeyValuePair`2[[System.String],[System.String]][]"
                },
                "Value": [
                  {
                    "Key": "Priority",
                    "Value": "0"
                  },
                  {
                    "Key": "Category",
                    "Value": "unit"
                  }
                ]
              }
            ]
          },
          "Attachments": [
            {
              "Uri": "datacollector://sample",
              "DisplayName": "Sample Collector",
              "Attachments": [
                {
                  "Description": "Log File",
                  "Uri": "file:///tmp/log.txt"
                }
              ]
            }
          ],
          "Messages": [
            {
              "Category": "StdOutMsgs",
              "Text": "sample stdout message"
            },
            {
              "Category": "StdErrMsgs",
              "Text": "sample stderr message"
            }
          ],
          "Properties": [
            {
              "Key": {
                "Id": "TestResult.Outcome",
                "Label": "Outcome",
                "Category": "",
                "Description": "",
                "Attributes": 0,
                "ValueType": "Microsoft.VisualStudio.TestPlatform.ObjectModel.TestOutcome, Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
              },
              "Value": 1
            },
            {
              "Key": {
                "Id": "TestResult.ErrorMessage",
                "Label": "Error Message",
                "Category": "",
                "Description": "",
                "Attributes": 0,
                "ValueType": "System.String"
              },
              "Value": "sampleError"
            },
            {
              "Key": {
                "Id": "TestResult.ErrorStackTrace",
                "Label": "Error Stack Trace",
                "Category": "",
                "Description": "",
                "Attributes": 0,
                "ValueType": "System.String"
              },
              "Value": "sampleStackTrace"
            },
            {
              "Key": {
                "Id": "TestResult.DisplayName",
                "Label": "TestResult Display Name",
                "Category": "",
                "Description": "",
                "Attributes": 1,
                "ValueType": "System.String"
              },
              "Value": "sampleTestResult"
            },
            {
              "Key": {
                "Id": "TestResult.ComputerName",
                "Label": "Computer Name",
                "Category": "",
                "Description": "",
                "Attributes": 0,
                "ValueType": "System.String"
              },
              "Value": "sampleComputerName"
            },
            {
              "Key": {
                "Id": "TestResult.Duration",
                "Label": "Duration",
                "Category": "",
                "Description": "",
                "Attributes": 0,
                "ValueType": "System.TimeSpan"
              },
              "Value": "00:02:03.4560000"
            },
            {
              "Key": {
                "Id": "TestResult.StartTime",
                "Label": "Start Time",
                "Category": "",
                "Description": "",
                "Attributes": 0,
                "ValueType": "System.DateTimeOffset"
              },
              "Value": "2023-01-15T10:30:00+00:00"
            },
            {
              "Key": {
                "Id": "TestResult.EndTime",
                "Label": "End Time",
                "Category": "",
                "Description": "",
                "Attributes": 0,
                "ValueType": "System.DateTimeOffset"
              },
              "Value": "2023-01-15T10:32:00+00:00"
            }
          ]
        }
        """;

    private static readonly string TestResultV2Json =
        """
        {
          "TestCase": {
            "Id": "be78d6fc-61b0-4882-9d07-40d796fd96ce",
            "FullyQualifiedName": "sampleTestClass.sampleTestCase",
            "DisplayName": "sampleTestCase",
            "ExecutorUri": "executor://sampleTestExecutor",
            "Source": "sampleTest.dll",
            "CodeFilePath": "/user/src/testFile.cs",
            "LineNumber": 999,
            "Properties": [
              {
                "Key": {
                  "Id": "TestObject.Traits",
                  "Label": "Traits",
                  "Category": "",
                  "Description": "",
                  "Attributes": 5,
                  "ValueType": "System.Collections.Generic.KeyValuePair`2[[System.String],[System.String]][]"
                },
                "Value": [
                  {
                    "Key": "Priority",
                    "Value": "0"
                  },
                  {
                    "Key": "Category",
                    "Value": "unit"
                  }
                ]
              }
            ]
          },
          "Attachments": [
            {
              "Uri": "datacollector://sample",
              "DisplayName": "Sample Collector",
              "Attachments": [
                {
                  "Description": "Log File",
                  "Uri": "file:///tmp/log.txt"
                }
              ]
            }
          ],
          "Outcome": 1,
          "ErrorMessage": "sampleError",
          "ErrorStackTrace": "sampleStackTrace",
          "DisplayName": "sampleTestResult",
          "Messages": [
            {
              "Category": "StdOutMsgs",
              "Text": "sample stdout message"
            },
            {
              "Category": "StdErrMsgs",
              "Text": "sample stderr message"
            }
          ],
          "ComputerName": "sampleComputerName",
          "Duration": "00:02:03.4560000",
          "StartTime": "2023-01-15T10:30:00+00:00",
          "EndTime": "2023-01-15T10:32:00+00:00",
          "Properties": []
        }
        """;

    private static readonly string TestRunCriteriaWithTestsV1Json =
        """
        {
          "Tests": [
            {
              "Properties": [
                {
                  "Key": {
                    "Id": "TestCase.FullyQualifiedName",
                    "Label": "FullyQualifiedName",
                    "Category": "",
                    "Description": "",
                    "Attributes": 1,
                    "ValueType": "System.String"
                  },
                  "Value": "sampleTestClass.sampleTestCase"
                },
                {
                  "Key": {
                    "Id": "TestCase.ExecutorUri",
                    "Label": "Executor Uri",
                    "Category": "",
                    "Description": "",
                    "Attributes": 1,
                    "ValueType": "System.Uri"
                  },
                  "Value": "executor://sampleTestExecutor"
                },
                {
                  "Key": {
                    "Id": "TestCase.Source",
                    "Label": "Source",
                    "Category": "",
                    "Description": "",
                    "Attributes": 0,
                    "ValueType": "System.String"
                  },
                  "Value": "sampleTest.dll"
                },
                {
                  "Key": {
                    "Id": "TestCase.CodeFilePath",
                    "Label": "File Path",
                    "Category": "",
                    "Description": "",
                    "Attributes": 0,
                    "ValueType": "System.String"
                  },
                  "Value": "/user/src/testFile.cs"
                },
                {
                  "Key": {
                    "Id": "TestCase.DisplayName",
                    "Label": "Name",
                    "Category": "",
                    "Description": "",
                    "Attributes": 0,
                    "ValueType": "System.String"
                  },
                  "Value": "sampleTestCase"
                },
                {
                  "Key": {
                    "Id": "TestCase.Id",
                    "Label": "Id",
                    "Category": "",
                    "Description": "",
                    "Attributes": 1,
                    "ValueType": "System.Guid"
                  },
                  "Value": "be78d6fc-61b0-4882-9d07-40d796fd96ce"
                },
                {
                  "Key": {
                    "Id": "TestCase.LineNumber",
                    "Label": "Line Number",
                    "Category": "",
                    "Description": "",
                    "Attributes": 1,
                    "ValueType": "System.Int32"
                  },
                  "Value": 999
                },
                {
                  "Key": {
                    "Id": "TestObject.Traits",
                    "Label": "Traits",
                    "Category": "",
                    "Description": "",
                    "Attributes": 5,
                    "ValueType": "System.Collections.Generic.KeyValuePair`2[[System.String],[System.String]][]"
                  },
                  "Value": [
                    {
                      "Key": "Priority",
                      "Value": "0"
                    },
                    {
                      "Key": "Category",
                      "Value": "unit"
                    }
                  ]
                }
              ]
            }
          ],
          "RunSettings": "<RunSettings><RunConfiguration></RunConfiguration></RunSettings>",
          "TestExecutionContext": {
            "FrequencyOfRunStatsChangeEvent": 10,
            "RunStatsChangeEventTimeout": "00:01:00",
            "InIsolation": false,
            "KeepAlive": true,
            "AreTestCaseLevelEventsRequired": false,
            "IsDebug": false,
            "TestCaseFilter": null,
            "FilterOptions": null
          },
          "Package": "samplePackage"
        }
        """;

    private static readonly string TestRunCriteriaWithTestsV2Json =
        """
        {
          "Tests": [
            {
              "Id": "be78d6fc-61b0-4882-9d07-40d796fd96ce",
              "FullyQualifiedName": "sampleTestClass.sampleTestCase",
              "DisplayName": "sampleTestCase",
              "ExecutorUri": "executor://sampleTestExecutor",
              "Source": "sampleTest.dll",
              "CodeFilePath": "/user/src/testFile.cs",
              "LineNumber": 999,
              "Properties": [
                {
                  "Key": {
                    "Id": "TestObject.Traits",
                    "Label": "Traits",
                    "Category": "",
                    "Description": "",
                    "Attributes": 5,
                    "ValueType": "System.Collections.Generic.KeyValuePair`2[[System.String],[System.String]][]"
                  },
                  "Value": [
                    {
                      "Key": "Priority",
                      "Value": "0"
                    },
                    {
                      "Key": "Category",
                      "Value": "unit"
                    }
                  ]
                }
              ]
            }
          ],
          "RunSettings": "<RunSettings><RunConfiguration></RunConfiguration></RunSettings>",
          "TestExecutionContext": {
            "FrequencyOfRunStatsChangeEvent": 10,
            "RunStatsChangeEventTimeout": "00:01:00",
            "InIsolation": false,
            "KeepAlive": true,
            "AreTestCaseLevelEventsRequired": false,
            "IsDebug": false,
            "TestCaseFilter": null,
            "FilterOptions": null
          },
          "Package": "samplePackage"
        }
        """;

    // TestRunCriteriaWithSources produces the same JSON for v1 and v2 (no TestCase objects to differ).
    private static readonly string TestRunCriteriaWithSourcesJson =
        """
        {
          "AdapterSourceMap": {
            "executor://sampleTestExecutor": [
              "sampleTest.dll"
            ]
          },
          "RunSettings": "<RunSettings><RunConfiguration></RunConfiguration></RunSettings>",
          "TestExecutionContext": {
            "FrequencyOfRunStatsChangeEvent": 10,
            "RunStatsChangeEventTimeout": "00:01:00",
            "InIsolation": false,
            "KeepAlive": true,
            "AreTestCaseLevelEventsRequired": false,
            "IsDebug": false,
            "TestCaseFilter": null,
            "FilterOptions": null
          },
          "Package": "samplePackage"
        }
        """;

    #endregion

    #region TestCase Golden Tests

    [TestMethod]
    [TestCategory("Serialization")]
    public void TestCaseSerializationV1ShouldMatchGoldenJson()
    {
        var json = Serialize(GoldenTestCase, 1);

        AssertJsonEqual(TestCaseV1Json, json);
    }

    [TestMethod]
    [TestCategory("Serialization")]
    public void TestCaseSerializationV2ShouldMatchGoldenJson()
    {
        var json = Serialize(GoldenTestCase, 2);

        AssertJsonEqual(TestCaseV2Json, json);
    }

    [TestMethod]
    [TestCategory("Serialization")]
    public void TestCaseRoundTripV1ShouldPreserveKeyProperties()
    {
        var deserialized = Deserialize<TestCase>(TestCaseV1Json, 1);

        Assert.AreEqual(GoldenTestCase.FullyQualifiedName, deserialized.FullyQualifiedName);
        Assert.AreEqual(GoldenTestCase.ExecutorUri, deserialized.ExecutorUri);
        Assert.AreEqual(GoldenTestCase.Source, deserialized.Source);
        Assert.AreEqual(GoldenTestCase.CodeFilePath, deserialized.CodeFilePath);
        Assert.AreEqual(GoldenTestCase.DisplayName, deserialized.DisplayName);
        Assert.AreEqual(GoldenTestCase.Id, deserialized.Id);
        Assert.AreEqual(GoldenTestCase.LineNumber, deserialized.LineNumber);
        var traits = deserialized.Traits.ToArray();
        Assert.HasCount(2, traits);
        Assert.AreEqual("Priority", traits[0].Name);
        Assert.AreEqual("0", traits[0].Value);
    }

    [TestMethod]
    [TestCategory("Serialization")]
    public void TestCaseRoundTripV2ShouldPreserveKeyProperties()
    {
        var deserialized = Deserialize<TestCase>(TestCaseV2Json, 2);

        Assert.AreEqual(GoldenTestCase.FullyQualifiedName, deserialized.FullyQualifiedName);
        Assert.AreEqual(GoldenTestCase.ExecutorUri, deserialized.ExecutorUri);
        Assert.AreEqual(GoldenTestCase.Source, deserialized.Source);
        Assert.AreEqual(GoldenTestCase.CodeFilePath, deserialized.CodeFilePath);
        Assert.AreEqual(GoldenTestCase.DisplayName, deserialized.DisplayName);
        Assert.AreEqual(GoldenTestCase.Id, deserialized.Id);
        Assert.AreEqual(GoldenTestCase.LineNumber, deserialized.LineNumber);
        var traits = deserialized.Traits.ToArray();
        Assert.HasCount(2, traits);
        Assert.AreEqual("Priority", traits[0].Name);
        Assert.AreEqual("0", traits[0].Value);
    }

    #endregion

    #region TestResult Golden Tests

    [TestMethod]
    [TestCategory("Serialization")]
    public void TestResultSerializationV1ShouldMatchGoldenJson()
    {
        var json = Serialize(GoldenTestResult, 1);

        AssertJsonEqual(TestResultV1Json, json);
    }

    [TestMethod]
    [TestCategory("Serialization")]
    public void TestResultSerializationV2ShouldMatchGoldenJson()
    {
        var json = Serialize(GoldenTestResult, 2);

        AssertJsonEqual(TestResultV2Json, json);
    }

    [TestMethod]
    [TestCategory("Serialization")]
    public void TestResultRoundTripV1ShouldPreserveKeyProperties()
    {
        var deserialized = Deserialize<TestResult>(TestResultV1Json, 1);

        Assert.AreEqual(GoldenTestResult.Outcome, deserialized.Outcome);
        Assert.AreEqual(GoldenTestResult.ErrorMessage, deserialized.ErrorMessage);
        Assert.AreEqual(GoldenTestResult.ErrorStackTrace, deserialized.ErrorStackTrace);
        Assert.AreEqual(GoldenTestResult.DisplayName, deserialized.DisplayName);
        Assert.AreEqual(GoldenTestResult.ComputerName, deserialized.ComputerName);
        Assert.AreEqual(GoldenTestResult.Duration, deserialized.Duration);
        Assert.AreEqual(GoldenTestResult.StartTime, deserialized.StartTime);
        Assert.AreEqual(GoldenTestResult.EndTime, deserialized.EndTime);
        Assert.AreEqual(GoldenTestResult.TestCase.Id, deserialized.TestCase.Id);
        Assert.HasCount(1, deserialized.Attachments);
        Assert.AreEqual("Sample Collector", deserialized.Attachments[0].DisplayName);
        Assert.AreEqual(new Uri("datacollector://sample"), deserialized.Attachments[0].Uri);
        Assert.HasCount(1, deserialized.Attachments[0].Attachments);
        Assert.AreEqual("Log File", deserialized.Attachments[0].Attachments[0].Description);
        Assert.HasCount(2, deserialized.Messages);
        Assert.AreEqual(TestResultMessage.StandardOutCategory, deserialized.Messages[0].Category);
        Assert.AreEqual("sample stdout message", deserialized.Messages[0].Text);
    }

    [TestMethod]
    [TestCategory("Serialization")]
    public void TestResultRoundTripV2ShouldPreserveKeyProperties()
    {
        var deserialized = Deserialize<TestResult>(TestResultV2Json, 2);

        Assert.AreEqual(GoldenTestResult.Outcome, deserialized.Outcome);
        Assert.AreEqual(GoldenTestResult.ErrorMessage, deserialized.ErrorMessage);
        Assert.AreEqual(GoldenTestResult.ErrorStackTrace, deserialized.ErrorStackTrace);
        Assert.AreEqual(GoldenTestResult.DisplayName, deserialized.DisplayName);
        Assert.AreEqual(GoldenTestResult.ComputerName, deserialized.ComputerName);
        Assert.AreEqual(GoldenTestResult.Duration, deserialized.Duration);
        Assert.AreEqual(GoldenTestResult.StartTime, deserialized.StartTime);
        Assert.AreEqual(GoldenTestResult.EndTime, deserialized.EndTime);
        Assert.AreEqual(GoldenTestResult.TestCase.Id, deserialized.TestCase.Id);
        Assert.HasCount(1, deserialized.Attachments);
        Assert.AreEqual("Sample Collector", deserialized.Attachments[0].DisplayName);
        Assert.HasCount(1, deserialized.Attachments[0].Attachments);
        Assert.HasCount(2, deserialized.Messages);
        Assert.AreEqual(TestResultMessage.StandardOutCategory, deserialized.Messages[0].Category);
    }

    #endregion

    #region TestRunCriteriaWithTests Golden Tests

    [TestMethod]
    [TestCategory("Serialization")]
    public void TestRunCriteriaWithTestsSerializationV1ShouldMatchGoldenJson()
    {
        var json = Serialize(GoldenTestRunCriteriaWithTests, 1);

        AssertJsonEqual(TestRunCriteriaWithTestsV1Json, json);
    }

    [TestMethod]
    [TestCategory("Serialization")]
    public void TestRunCriteriaWithTestsSerializationV2ShouldMatchGoldenJson()
    {
        var json = Serialize(GoldenTestRunCriteriaWithTests, 2);

        AssertJsonEqual(TestRunCriteriaWithTestsV2Json, json);
    }

    [TestMethod]
    [TestCategory("Serialization")]
    public void TestRunCriteriaWithTestsRoundTripV1ShouldPreserveKeyProperties()
    {
        var deserialized = Deserialize<TestRunCriteriaWithTests>(TestRunCriteriaWithTestsV1Json, 1);

        Assert.AreEqual("samplePackage", deserialized.Package);
        Assert.AreEqual("<RunSettings><RunConfiguration></RunConfiguration></RunSettings>", deserialized.RunSettings);
        Assert.AreEqual(10, deserialized.TestExecutionContext.FrequencyOfRunStatsChangeEvent);
        Assert.AreEqual(TimeSpan.FromSeconds(60), deserialized.TestExecutionContext.RunStatsChangeEventTimeout);
        Assert.IsFalse(deserialized.TestExecutionContext.InIsolation);
        Assert.IsTrue(deserialized.TestExecutionContext.KeepAlive);

        var tests = new List<TestCase>(deserialized.Tests);
        Assert.HasCount(1, tests);
        Assert.AreEqual(GoldenTestCase.FullyQualifiedName, tests[0].FullyQualifiedName);
        Assert.AreEqual(GoldenTestCase.Id, tests[0].Id);
    }

    [TestMethod]
    [TestCategory("Serialization")]
    public void TestRunCriteriaWithTestsRoundTripV2ShouldPreserveKeyProperties()
    {
        var deserialized = Deserialize<TestRunCriteriaWithTests>(TestRunCriteriaWithTestsV2Json, 2);

        Assert.AreEqual("samplePackage", deserialized.Package);
        Assert.AreEqual("<RunSettings><RunConfiguration></RunConfiguration></RunSettings>", deserialized.RunSettings);
        Assert.AreEqual(10, deserialized.TestExecutionContext.FrequencyOfRunStatsChangeEvent);
        Assert.AreEqual(TimeSpan.FromSeconds(60), deserialized.TestExecutionContext.RunStatsChangeEventTimeout);
        Assert.IsFalse(deserialized.TestExecutionContext.InIsolation);
        Assert.IsTrue(deserialized.TestExecutionContext.KeepAlive);

        var tests = new List<TestCase>(deserialized.Tests);
        Assert.HasCount(1, tests);
        Assert.AreEqual(GoldenTestCase.FullyQualifiedName, tests[0].FullyQualifiedName);
        Assert.AreEqual(GoldenTestCase.Id, tests[0].Id);
    }

    #endregion

    #region TestRunCriteriaWithSources Golden Tests

    [TestMethod]
    [TestCategory("Serialization")]
    [DataRow(1)]
    [DataRow(2)]
    public void TestRunCriteriaWithSourcesSerializationShouldMatchGoldenJson(int version)
    {
        var json = Serialize(GoldenTestRunCriteriaWithSources, version);

        AssertJsonEqual(TestRunCriteriaWithSourcesJson, json);
    }

    [TestMethod]
    [TestCategory("Serialization")]
    [DataRow(1)]
    [DataRow(2)]
    public void TestRunCriteriaWithSourcesRoundTripShouldPreserveKeyProperties(int version)
    {
        var deserialized = Deserialize<TestRunCriteriaWithSources>(TestRunCriteriaWithSourcesJson, version);

        Assert.AreEqual("samplePackage", deserialized.Package);
        Assert.AreEqual("<RunSettings><RunConfiguration></RunConfiguration></RunSettings>", deserialized.RunSettings);
        Assert.AreEqual(10, deserialized.TestExecutionContext.FrequencyOfRunStatsChangeEvent);
        Assert.AreEqual(TimeSpan.FromSeconds(60), deserialized.TestExecutionContext.RunStatsChangeEventTimeout);
        Assert.IsTrue(deserialized.AdapterSourceMap.ContainsKey("executor://sampleTestExecutor"));
        Assert.AreEqual("sampleTest.dll", new List<string>(deserialized.AdapterSourceMap["executor://sampleTestExecutor"])[0]);
    }

    #endregion

    #region Helpers

    private static string Serialize<T>(T data, int version)
    {
        return JsonDataSerializer.Instance.Serialize(data, version);
    }

    private static T Deserialize<T>(string json, int version)
    {
        return JsonDataSerializer.Instance.Deserialize<T>(json, version)!;
    }

    private static void AssertJsonEqual(string expected, string actual)
    {
        // Normalize both strings by parsing and re-serializing to remove whitespace differences
        static string Normalize(string json)
            => Newtonsoft.Json.Linq.JToken.Parse(json).ToString(Newtonsoft.Json.Formatting.None);

        var normalizedExpected = Normalize(expected);
        var normalizedActual = Normalize(actual);
        Assert.AreEqual(normalizedExpected, normalizedActual,
            $"JSON mismatch.\nExpected:\n{expected}\nActual:\n{actual}");
    }

    #endregion
}
