id: ScheduledSearch.AutoClose
name: GitOps.PullRequestIssueManagement
description: Housekeeping of issues that should be closed
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
      - description: >-
          Search for PR where -
          * Pull Request is Open
          * Pull request has the label "State: No Recent Activity"
          * Pull request has the label "Needs: Author Feedback"
          * Has not had activity in the last 7 days

          Then -
          * Close the PR
        frequencies:
          - hourly:
              hour: 6
        filters:
          - isPullRequest
          - isOpen
          - hasLabel:
              label: "State: No Recent Activity"
          - hasLabel:
              label: "Needs: Author Feedback"
          - noActivitySince:
              days: 7
        actions:
          - closeIssue
      - description: >-
          Search for Issues where -
          * Issue is Open
          * Issue has the label "State: No Recent Activity"
          * Issue has the label "Needs: Author Feedback"
          * Has not had activity in the last 7 days

          Then -
          * Close the Issue
        frequencies:
          - hourly:
              hour: 6
        filters:
          - isIssue
          - isOpen
          - hasLabel:
              label: "State: No Recent Activity"
          - hasLabel:
              label: "Needs: Author Feedback"
          - noActivitySince:
              days: 7
        actions:
          - closeIssue
      - description: >-
          Search for Issues where -
          * Issue is Open
          * Issue has the label "State: Won't Fix"
          * Has not had activity in the last 1 day

          Then -
          * Close the Issue
        frequencies:
          - hourly:
              hour: 6
        filters:
          - isIssue
          - isOpen
          - hasLabel:
              label: "State: Won't Fix"
          - noActivitySince:
              days: 1
        actions:
          - addReply:
              reply: This issue has been marked as won't fix and has not had any activity for **1 day**. It will be closed for housekeeping purposes.
          - closeIssue
      - description: >-
          Search for Issues where -
          * Issue is Open
          * Issue has the label "Resolution: Duplicate"
          * Has not had activity in the last 1 day

          Then -
          * Close the Issue
        frequencies:
          - hourly:
              hour: 6
        filters:
          - isIssue
          - isOpen
          - hasLabel:
              label: "Resolution: Duplicate"
          - noActivitySince:
              days: 1
        actions:
          - addReply:
              reply: This issue has been marked as duplicate and has not had any activity for **1 day**. It will be closed for housekeeping purposes.
          - closeIssue
onFailure:
onSuccess: