' <auto-generated> This file has been auto generated. </auto-generated>
Imports System
Module AutoGeneratedProgram
<Microsoft.VisualStudio.TestPlatform.TestSDKAutoGeneratedCode>
Sub Main(args As String())
End Sub
End Module