# Pipeline YAML for PR

jobs:
- job: Windows
  pool:
    name: VSEng-MicroBuildVS2017
    demands: 
    - DotNetFramework
    - Cmd
    - msbuild
    - visualstudio
  variables:
    buildConfiguration: 'debug'
  steps:
  - task: BatchScript@1
    displayName: 'Run script build.cmd'
    inputs:
      filename: build.cmd
      arguments: '-verbose -configuration $(buildConfiguration)'
      modifyEnvironment: false
      failOnStandardError: true

  - task: BatchScript@1
    displayName: 'Run Unit Tests'
    inputs:
      filename: test.cmd
      arguments: '-verbose -configuration $(buildConfiguration)'
      modifyEnvironment: false
      failOnStandardError: true
      
  - task: BatchScript@1
    displayName: 'Run Acceptance Tests'
    inputs:
      filename: test.cmd
      arguments: '-verbose -configuration $(buildConfiguration) -p AcceptanceTests -v -f net451'
      modifyEnvironment: false
      failOnStandardError: true
      
  - task: BatchScript@1
    displayName: 'Run Platform Tests'
    inputs:
      filename: test.cmd
      arguments: '-verbose -configuration $(buildConfiguration) -p platformtests'
      modifyEnvironment: false
      failOnStandardError: true
            
  - task: BatchScript@1
    displayName: 'Run Smoke Tests'
    inputs:
      filename: test.cmd
      arguments: '-verbose -configuration $(buildConfiguration) -p smoke'
      modifyEnvironment: false
      failOnStandardError: true
      
  - task: PublishTestResults@2
    displayName: 'Publish Test Results **\*.trx'
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: '**\*.trx'
    condition: succeededOrFailed()
    
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  variables:
      buildConfiguration: 'Release'
  steps:
  - script: ./build.sh -c $(buildConfiguration)
    displayName: './build.sh -c $(buildConfiguration)'
  - script: ./test.sh -c $(buildConfiguration)
    displayName: './test.sh -c $(buildConfiguration)'
  - task: PublishTestResults@2
    
