// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;
using System.Globalization;
using System.Reflection;

using Microsoft.VisualStudio.TestPlatform.CommandLine;
using Microsoft.VisualStudio.TestPlatform.CommandLine.Processors;
using Microsoft.VisualStudio.TestPlatform.Common;
using Microsoft.VisualStudio.TestPlatform.Utilities.Helpers.Interfaces;
using Microsoft.VisualStudio.TestTools.UnitTesting;

using Moq;

namespace vstest.console.UnitTests.Processors;

/// <summary>
/// Regression test for GH-813 / PR #1390:
/// The code coverage default settings template must exclude auto-generated code
/// by including exclusion patterns in the Attributes section. PR #1390 added the
/// TestSDKAutoGeneratedCode attribute to auto-generated code and added corresponding
/// exclusion patterns to the default code coverage settings template.
/// If the fix is reverted, the template would not contain these exclusion patterns,
/// and auto-generated code would be included in code coverage results.
/// </summary>
[TestClass]
public class RegressionBugFixTests
{
    public TestContext TestContext { get; set; } = null!;

    [TestMethod]
    public void CodeCoverageTemplate_MustExcludeAutoGeneratedCodeAttributes()
    {
        // GH-813: The fix added attribute exclusion patterns to the default code coverage
        // settings template. Access the private field via reflection to verify the patterns.
        var field = typeof(EnableCodeCoverageArgumentExecutor)
            .GetField("CodeCoverageCollectorSettingsTemplate",
                BindingFlags.NonPublic | BindingFlags.Static);

        Assert.IsNotNull(field,
            "GH-813: CodeCoverageCollectorSettingsTemplate field must exist.");

        var template = (string)field.GetValue(null)!;
        Assert.IsNotNull(template,
            "GH-813: CodeCoverageCollectorSettingsTemplate must not be null.");

        // The template must contain the TestSDKAutoGeneratedCode attribute exclusion pattern
        // that was added by PR #1390 to exclude auto-generated code from coverage.
        Assert.Contains("TestSDKAutoGeneratedCode", template,
            "GH-813: Code coverage template must exclude TestSDKAutoGeneratedCode-attributed code.");
    }

    [TestMethod]
    public void Initialize_CodeCoverage_ResultingRunSettingsMustContainAutoGeneratedCodeExclusion()
    {
        // GH-813: When code coverage is enabled via Initialize, the resulting runsettings
        // must contain attribute exclusion patterns for auto-generated code.
        var settingsProvider = new TestableRunSettingsProvider();
        var executor = new EnableCodeCoverageArgumentExecutor(
            CommandLineOptions.Instance, settingsProvider, new Mock<IFileHelper>().Object);
        CollectArgumentExecutor.EnabledDataCollectors.Clear();

        var runsettingsString = string.Format(CultureInfo.CurrentCulture,
            string.Join(Environment.NewLine,
                "<?xml version=\"1.0\" encoding=\"utf-16\"?>",
                "<RunSettings>",
                "  <DataCollectionRunSettings>",
                "    <DataCollectors >{0}</DataCollectors>",
                "  </DataCollectionRunSettings>",
                "</RunSettings>"),
            "");
        var runsettings = new RunSettings();
        runsettings.LoadSettingsXml(runsettingsString);
        settingsProvider.SetActiveRunSettings(runsettings);

        // Act
        executor.Initialize(string.Empty);

        // Assert: the resulting runsettings must contain the auto-generated code exclusion
        var resultXml = settingsProvider.ActiveRunSettings!.SettingsXml!;
        Assert.Contains("TestSDKAutoGeneratedCode", resultXml,
            "GH-813: Resulting runsettings must contain auto-generated code attribute exclusion.");
        Assert.Contains("<Attribute>", resultXml,
            "GH-813: Resulting runsettings must contain Attribute exclusion elements.");
    }
}
