//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.TestPlatform.DataCollection.V1 {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.TestPlatform.DataCollection.v1.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Diagnostic data adapters could not be loaded. Failed to create required configuration. More details: {0}..
        /// </summary>
        public static string ConfigureSessionError {
            get {
                return ResourceManager.GetString("ConfigureSessionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not find diagnostic data adapter &apos;{0}&apos;.  Make sure diagnostic data adapter is installed and try again..
        /// </summary>
        public static string DataCollectorAssemblyNotFound {
            get {
                return ResourceManager.GetString("DataCollectorAssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Failed to dispose diagnostic data adapter &apos;{0}&apos;. Error: {1}..
        /// </summary>
        public static string DataCollectorDisposeError {
            get {
                return ResourceManager.GetString("DataCollectorDisposeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Diagnostic data adapter &apos;{0}&apos; failed to provide intialization information. Error: {1}.
        /// </summary>
        public static string DataCollectorErrorOnGetVariable {
            get {
                return ResourceManager.GetString("DataCollectorErrorOnGetVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The diagnostic data adapter &apos;{0}&apos;  threw an exception during type loading, construction, or initialization: {1}..
        /// </summary>
        public static string DataCollectorInitializationError {
            get {
                return ResourceManager.GetString("DataCollectorInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not find diagnostic data adapter of type &apos;{0}&apos; and Uri &apos;{1}&apos;.
        /// </summary>
        public static string DataCollectorNotFound {
            get {
                return ResourceManager.GetString("DataCollectorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The diagnostic data adapter &apos;{0}&apos; requested environment variable &apos;{1}&apos; with value &apos;{2}&apos; to be set in test execution environment, but another diagnostic data adapter &apos;{3}&apos; has already requested same environment variable with different value &apos;{4}&apos;..
        /// </summary>
        public static string DataCollectorRequestedDuplicateEnvironmentVariable {
            get {
                return ResourceManager.GetString("DataCollectorRequestedDuplicateEnvironmentVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This adapter will not be used for this test run. The following error occurred: {0}..
        /// </summary>
        public static string DataCollectorRunError {
            get {
                return ResourceManager.GetString("DataCollectorRunError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Failed to get type for diagnostic data adapter &apos;{0}&apos;. Error: {1}..
        /// </summary>
        public static string DataCollectorTypeNotFound {
            get {
                return ResourceManager.GetString("DataCollectorTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sending message of Message Type &apos;{0}&apos; is not supported..
        /// </summary>
        public static string DataCollectorUnsupportedMessageType {
            get {
                return ResourceManager.GetString("DataCollectorUnsupportedMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Timed out invoking diagnostic data adapter event handler &apos;{0}&apos;.
        ///
        ///To increase the timeout values for all diagnostic data adapters, see the following link: http://go.microsoft.com/fwlink/?LinkId=169311.
        /// </summary>
        public static string Execution_DataCollectorEventTimeout {
            get {
                return ResourceManager.GetString("Execution_DataCollectorEventTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to There are multiple configurations that have diagnostic data adapter  type &apos;{0}&apos; or Uri &apos;{1}&apos;. Duplicate configurations will be ignored in the test run..
        /// </summary>
        public static string IgnoredDuplicateConfiguration {
            get {
                return ResourceManager.GetString("IgnoredDuplicateConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Diagnostic data adapter caught an exception of type &apos;{0}&apos;: &apos;{1}&apos;. More details: {2}..
        /// </summary>
        public static string ReportDataCollectorException {
            get {
                return ResourceManager.GetString("ReportDataCollectorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Diagnostic data adapter can send collection logs as files. Sending data as stream is not supported..
        /// </summary>
        public static string SupportedTransferTypeIsFileTransfer {
            get {
                return ResourceManager.GetString("SupportedTransferTypeIsFileTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Types deriving from the data collection context cannot be used for sending data and messages.  The DataCollectionContext used for sending data and messages must come from one of the events raised to the data collector..
        /// </summary>
        public static string WrongDataCollectionContextType {
            get {
                return ResourceManager.GetString("WrongDataCollectionContextType", resourceCulture);
            }
        }
    }
}
