//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.Coverage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfigurationEditorUIResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationEditorUIResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    /*global::System.Resources.ResourceManager temp = null; new global::System.Resources.ResourceManager("Microsoft.VisualStudio.TraceCollector.VanguardCollector.ConfigurationEditor.Confi" +
                            "gurationEditorUIResource", typeof(ConfigurationEditorUIResource).GetTypeInfo().Assembly);
                    resourceMan = temp;*/
                    resourceMan = null;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add application under test.
        /// </summary>
        public static string AddEntryPointMessage {
            get {
                return ResourceManager.GetString("AddEntryPointMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add application under test.
        /// </summary>
        public static string AddEntryPointTitle {
            get {
                return ResourceManager.GetString("AddEntryPointTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Path of Invoked Binary.
        /// </summary>
        public static string AddPattern {
            get {
                return ResourceManager.GetString("AddPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect data from an ASP.NET application running on Internet Information Services.
        /// </summary>
        public static string CollectFromAspNetInIIS {
            get {
                return ResourceManager.GetString("CollectFromAspNetInIIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The config file contains complex regular expression which cannot be shown in UI..
        /// </summary>
        public static string ComplexRegularExpression {
            get {
                return ResourceManager.GetString("ComplexRegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the path of a .dll or .exe file – wildcards (*) are allowed:.
        /// </summary>
        public static string EnterPattern {
            get {
                return ResourceManager.GetString("EnterPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the names of the .exe files for which to collect data (separated by semicolons):.
        /// </summary>
        public static string EntryPoint {
            get {
                return ResourceManager.GetString("EntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company name specified is invalid..
        /// </summary>
        public static string InvalidCompanyName {
            get {
                return ResourceManager.GetString("InvalidCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration..
        /// </summary>
        public static string InvalidConfig {
            get {
                return ResourceManager.GetString("InvalidConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry point is invalid..
        /// </summary>
        public static string InvalidEntryPoint {
            get {
                return ResourceManager.GetString("InvalidEntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The public key specified is invalid..
        /// </summary>
        public static string InvalidPublicKey {
            get {
                return ResourceManager.GetString("InvalidPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid regular expression in configuration..
        /// </summary>
        public static string InvalidRegexConfig {
            get {
                return ResourceManager.GetString("InvalidRegexConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration contains a setting that cannot be recognized..
        /// </summary>
        public static string InvalidSettingType {
            get {
                return ResourceManager.GetString("InvalidSettingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol search path is invalid..
        /// </summary>
        public static string InvalidSymbolPath {
            get {
                return ResourceManager.GetString("InvalidSymbolPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the list of dlls which should be included for code coverage. Use regular expressions to specify input. 
        ///Example: .*\\WebAppDAL\.dll.
        /// </summary>
        public static string OtherModule {
            get {
                return ResourceManager.GetString("OtherModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the project outputs in the current solution for which to collect code coverage data:.
        /// </summary>
        public static string OutputModule {
            get {
                return ResourceManager.GetString("OutputModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For example: .
        /// </summary>
        public static string Sample {
            get {
                return ResourceManager.GetString("Sample", resourceCulture);
            }
        }
    }
}
