//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.TestPlatform.Utilities.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.TestPlatform.Utilities.Resources.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Run settings XML does not contain &quot;RunSettings&quot; node..
        /// </summary>
        public static string InvalidRunSettingsXml {
            get {
                return ResourceManager.GetString("InvalidRunSettingsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid setting &apos;{0}&apos;. Invalid value &apos;{1}&apos; specified for &apos;{2}&apos;..
        /// </summary>
        public static string InvalidSettingsIncorrectValue {
            get {
                return ResourceManager.GetString("InvalidSettingsIncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not find &apos;RunSettings&apos; node..
        /// </summary>
        public static string MissingRunSettingsNode {
            get {
                return ResourceManager.GetString("MissingRunSettingsNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not find &apos;RunSettings&apos; node..
        /// </summary>
        public static string NoRunSettingsNodeFound {
            get {
                return ResourceManager.GetString("NoRunSettingsNodeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred while loading the settings.  Error: {0}..
        /// </summary>
        public static string RunSettingsParseError {
            get {
                return ResourceManager.GetString("RunSettingsParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Incompatible Target platform settings &apos;{0}&apos; with system architecture &apos;{1}&apos;..
        /// </summary>
        public static string SystemArchitectureIncompatibleWithTargetPlatform {
            get {
                return ResourceManager.GetString("SystemArchitectureIncompatibleWithTargetPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unexpected settings file specified..
        /// </summary>
        public static string UnExpectedSettingsFile {
            get {
                return ResourceManager.GetString("UnExpectedSettingsFile", resourceCulture);
            }
        }
    }
}
