# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
parameters:
  continueOnError: false
  enablePublishBuildArtifacts: false
  enablePublishUsingPipelines: false
  enableSourceBuild: false
  sourceBuildParameters: []
  graphFileGeneration:
    enabled: false
    includeToolset: false
  jobs: []
  publishBuildAssetsDependsOn: ''
  publishAssetsImmediately: false
  artifactsPublishingAdditionalParameters: ''
  signingValidationAdditionalParameters: ''
  runAsPublic: false
  enableSourceIndex: false
  sourceIndexParams: {}
jobs:
- ${{ each job in parameters.jobs }}:
  - template: /eng/common/templates/job/job.yml@self
    parameters:
      ${{ each parameter in parameters }}:
        ${{ if ne(parameter.key, 'jobs') }}:
          ${{ parameter.key }}: ${{ parameter.value }}
      ${{ each property in job }}:
        ${{ if ne(property.key, 'job') }}:
          ${{ property.key }}: ${{ property.value }}
      name: ${{ job.job }}
- ${{ if eq(parameters.enableSourceBuild, true) }}:
  - template: /eng/common/templates/jobs/source-build.yml@self
    parameters:
      allCompletedJobId: Source_Build_Complete
      ${{ each parameter in parameters.sourceBuildParameters }}:
        ${{ parameter.key }}: ${{ parameter.value }}
- ${{ if eq(parameters.enableSourceIndex, 'true') }}:
  - template: /eng/common/templates/job/source-index-stage1.yml@self
    parameters:
      runAsPublic: ${{ parameters.runAsPublic }}
      ${{ each parameter in parameters.sourceIndexParams }}:
        ${{ parameter.key }}: ${{ parameter.value }}
- ${{ if and(eq(parameters.runAsPublic, 'false'), ne(variables['System.TeamProject'], 'public'), notin(variables['Build.Reason'], 'PullRequest')) }}:
  - ${{ if or(eq(parameters.enablePublishBuildAssets, true), eq(parameters.artifacts.publish.manifests, 'true'), ne(parameters.artifacts.publish.manifests, '')) }}:
    - template: /eng/common/templates/job/publish-build-assets.yml@self
      parameters:
        continueOnError: ${{ parameters.continueOnError }}
        dependsOn:
        - ${{ if ne(parameters.publishBuildAssetsDependsOn, '') }}:
          - ${{ each job in parameters.publishBuildAssetsDependsOn }}:
            - ${{ job.job }}
        - ${{ if eq(parameters.publishBuildAssetsDependsOn, '') }}:
          - ${{ each job in parameters.jobs }}:
            - ${{ job.job }}
        - ${{ if eq(parameters.enableSourceBuild, true) }}:
          - Source_Build_Complete
        runAsPublic: ${{ parameters.runAsPublic }}
        publishUsingPipelines: ${{ parameters.enablePublishUsingPipelines }}
        publishAssetsImmediately: ${{ parameters.publishAssetsImmediately }}
        enablePublishBuildArtifacts: ${{ parameters.enablePublishBuildArtifacts }}
        artifactsPublishingAdditionalParameters: ${{ parameters.artifactsPublishingAdditionalParameters }}
        signingValidationAdditionalParameters: ${{ parameters.signingValidationAdditionalParameters }}