# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
parameters:
  allCompletedJobId: ''
  jobNamePrefix: 'Source_Build'
  defaultManagedPlatform:
    name: 'Managed'
    container: 'mcr.microsoft.com/dotnet-buildtools/prereqs:centos-stream8'
  platforms: []
jobs:
- ${{ if ne(parameters.allCompletedJobId, '') }}:
  - job: ${{ parameters.allCompletedJobId }}
    displayName: Source-Build Complete
    pool: server
    dependsOn:
    - ${{ each platform in parameters.platforms }}:
      - ${{ parameters.jobNamePrefix }}_${{ platform.name }}
    - ${{ if eq(length(parameters.platforms), 0) }}:
      - ${{ parameters.jobNamePrefix }}_${{ parameters.defaultManagedPlatform.name }}
- ${{ each platform in parameters.platforms }}:
  - template: /eng/common/templates/job/source-build.yml@self
    parameters:
      jobNamePrefix: ${{ parameters.jobNamePrefix }}
      platform: ${{ platform }}
- ${{ if eq(length(parameters.platforms), 0) }}:
  - template: /eng/common/templates/job/source-build.yml@self
    parameters:
      jobNamePrefix: ${{ parameters.jobNamePrefix }}
      platform: ${{ parameters.defaultManagedPlatform }}