// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System;
using System.ComponentModel;

namespace Microsoft.VisualStudio.TestPlatform;

/// <summary>
/// Only to be used by the Test platform, to exclude auto generated code from code coverage.
/// New code should use <see cref="System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute"/> instead;
/// this attribute is retained only so that test assemblies built against older Microsoft.NET.Test.Sdk
/// versions (which emit this attribute on the generated Main) continue to be excluded from code coverage.
/// </summary>
[AttributeUsage(AttributeTargets.All)]
[EditorBrowsable(EditorBrowsableState.Never)]
public class TestSDKAutoGeneratedCode : Attribute
{
}
