// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

namespace Microsoft.VisualStudio.TestPlatform
{
    using System;
    /// <summary>
    /// Only to be used to Test platform, to exclude auto generated code from CodeCoverage
    /// </summary>
    public class TestSDKAutoGeneratedCode : Attribute
    {
    }
}
