//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.TraceDataCollector.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.TraceDataCollector.Resources.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use to collect code coverage data for ASP.NET applications running on IIS. Choose &apos;Configure&apos; to provide location of symbol files..
        /// </summary>
        internal static string CodeCoverageCollectorDescription {
            get {
                return ResourceManager.GetString("CodeCoverageCollectorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Coverage.
        /// </summary>
        internal static string CodeCoverageCollectorFriendlyName {
            get {
                return ResourceManager.GetString("CodeCoverageCollectorFriendlyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch CodeCoverage.exe with the following error. No code coverage data will be collected: {0}.
        /// </summary>
        internal static string ErrorLaunchVanguard {
            get {
                return ResourceManager.GetString("ErrorLaunchVanguard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No application under test is specified..
        /// </summary>
        internal static string ErrorNoEntryPoint {
            get {
                return ResourceManager.GetString("ErrorNoEntryPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find CodeCoverage.exe..
        /// </summary>
        internal static string ErrorNoVanguard {
            get {
                return ResourceManager.GetString("ErrorNoVanguard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The adapter &apos;Code Coverage&apos; will not be used for this test run as Microsoft Test Manager is not running as administrator. To collect code coverage, re-start Microsoft Test Manager by choosing to &apos;Run as Administrator&apos; and then start the test run..
        /// </summary>
        internal static string ErrorRegisterExecutable {
            get {
                return ResourceManager.GetString("ErrorRegisterExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch CodeCoverage.exe. No code coverage will be collected..
        /// </summary>
        internal static string GeneralErrorLaunchVanguard {
            get {
                return ResourceManager.GetString("GeneralErrorLaunchVanguard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute command {0} on Lab Agent..
        /// </summary>
        internal static string LabAgentTaskExecutionFailed {
            get {
                return ResourceManager.GetString("LabAgentTaskExecutionFailed", resourceCulture);
            }
        }
    }
}
