' <auto-generated> This file has been auto generated. </auto-generated>
Namespace Global
Module __MicrosoftTestPlatformAutoGeneratedProgram
<System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage>
Sub Main(args As String())
End Sub
End Module
End Namespace
