// <auto-generated> This file has been auto generated. </auto-generated>
using System;
using System.Diagnostics.CodeAnalysis;

[ExcludeFromCodeCoverage]
class AutoGeneratedProgram {static void Main(string[] args){}}