//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.TestPlatform.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.TestPlatform.Common.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Access denied while trying to create &quot;TestResults&quot; folder in mentioned location. You are getting this exception because you are running vstest.console.exe from a folder which requires having write access. To solve the issue: please  run vstest.console.exe from a folder where you have write privileges. For more information, please look at the error message:.
        /// </summary>
        internal static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling the operation as requested..
        /// </summary>
        internal static string CancellationRequested {
            get {
                return ResourceManager.GetString("CancellationRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data collection : {0}.
        /// </summary>
        internal static string DataCollectionMessageFormat {
            get {
                return ResourceManager.GetString("DataCollectionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data collector &apos;{0}&apos; failed to provide initialization information. Error: {1}.
        /// </summary>
        internal static string DataCollectorErrorOnGetVariable {
            get {
                return ResourceManager.GetString("DataCollectorErrorOnGetVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data collector &apos;{0}&apos; threw an exception during type loading, construction, or initialization: {1}..
        /// </summary>
        internal static string DataCollectorInitializationError {
            get {
                return ResourceManager.GetString("DataCollectorInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data collector &apos;{0}&apos; message: {1}..
        /// </summary>
        internal static string DataCollectorMessageFormat {
            get {
                return ResourceManager.GetString("DataCollectorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find data collector &apos;{0}&apos;.
        /// </summary>
        internal static string DataCollectorNotFound {
            get {
                return ResourceManager.GetString("DataCollectorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data collector &apos;{0}&apos; requested environment variable &apos;{1}&apos; with value &apos;{2}&apos; to be set in test execution environment, but another data collector &apos;{3}&apos; has already requested same environment variable with different value &apos;{4}&apos;..
        /// </summary>
        internal static string DataCollectorRequestedDuplicateEnvironmentVariable {
            get {
                return ResourceManager.GetString("DataCollectorRequestedDuplicateEnvironmentVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate test extension URI &apos;{0}&apos;.  Ignoring the duplicate extension..
        /// </summary>
        internal static string DuplicateExtensionUri {
            get {
                return ResourceManager.GetString("DuplicateExtensionUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate settings provider named &apos;{0}&apos;.  Ignoring the duplicate provider..
        /// </summary>
        internal static string DuplicateSettingsName {
            get {
                return ResourceManager.GetString("DuplicateSettingsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate run settings section named &apos;{0}&apos; found.  Ignoring the duplicate settings..
        /// </summary>
        internal static string DuplicateSettingsProvided {
            get {
                return ResourceManager.GetString("DuplicateSettingsProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Empty parenthesis ( ).
        /// </summary>
        internal static string EmptyParenthesis {
            get {
                return ResourceManager.GetString("EmptyParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find the list of installed unit test extensions. Reason: {0}.
        /// </summary>
        internal static string FailedToFindInstalledUnitTestExtensions {
            get {
                return ResourceManager.GetString("FailedToFindInstalledUnitTestExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load extensions from file &apos;{0}&apos;. Please use /diag for more information..
        /// </summary>
        internal static string FailedToLoadAdapaterFile {
            get {
                return ResourceManager.GetString("FailedToLoadAdapaterFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while creating Fast filter..
        /// </summary>
        internal static string FastFilterException {
            get {
                return ResourceManager.GetString("FastFilterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple configurations that have data collector FriendlyName as &apos;{0}&apos;. Duplicate configurations will be ignored in the test run..
        /// </summary>
        internal static string IgnoredDuplicateConfiguration {
            get {
                return ResourceManager.GetString("IgnoredDuplicateConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invalid Condition &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidCondition {
            get {
                return ResourceManager.GetString("InvalidCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Extension has an invalid URI &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string InvalidExtensionUriFormat {
            get {
                return ResourceManager.GetString("InvalidExtensionUriFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invalid operator &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidOperator {
            get {
                return ResourceManager.GetString("InvalidOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred while initializing logger with {0}: &apos;{1}&apos;.  The logger will not be used.  Exception: {2}.
        /// </summary>
        internal static string LoggerInitializationError {
            get {
                return ResourceManager.GetString("LoggerInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a test logger with AssemblyQualifiedName, URI or FriendlyName &apos;{0}&apos;..
        /// </summary>
        internal static string LoggerNotFound {
            get {
                return ResourceManager.GetString("LoggerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Test Logger URI &apos;{0}&apos; is not valid.  The Test Logger will be ignored..
        /// </summary>
        internal static string LoggerUriInvalid {
            get {
                return ResourceManager.GetString("LoggerUriInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Missing &apos;)&apos;.
        /// </summary>
        internal static string MissingCloseParenthesis {
            get {
                return ResourceManager.GetString("MissingCloseParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Missing &apos;(&apos;.
        /// </summary>
        internal static string MissingOpenParenthesis {
            get {
                return ResourceManager.GetString("MissingOpenParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Missing operand.
        /// </summary>
        internal static string MissingOperand {
            get {
                return ResourceManager.GetString("MissingOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Operator &apos;|&apos; or &apos;&amp;&apos;.
        /// </summary>
        internal static string MissingOperator {
            get {
                return ResourceManager.GetString("MissingOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data collector caught an exception of type &apos;{0}&apos;: &apos;{1}&apos;. More details: {2}..
        /// </summary>
        internal static string ReportDataCollectorException {
            get {
                return ResourceManager.GetString("ReportDataCollectorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Run Settings have already been loaded..
        /// </summary>
        internal static string RunSettingsAlreadyLoaded {
            get {
                return ResourceManager.GetString("RunSettingsAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the run settings.  Error: {0}.
        /// </summary>
        internal static string RunSettingsParseError {
            get {
                return ResourceManager.GetString("RunSettingsParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid settings node specified. The name property of the settings node must be non-empty..
        /// </summary>
        internal static string SettingsNodeInvalidName {
            get {
                return ResourceManager.GetString("SettingsNodeInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while initializing the settings provider named &apos;{0}&apos;. Error: {1}.
        /// </summary>
        internal static string SettingsProviderInitializationError {
            get {
                return ResourceManager.GetString("SettingsProviderInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Provider named &apos;{0}&apos; was not found.  The settings can not be loaded..
        /// </summary>
        internal static string SettingsProviderNotFound {
            get {
                return ResourceManager.GetString("SettingsProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect format for TestCaseFilter {0}. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed..
        /// </summary>
        internal static string TestCaseFilterFormatException {
            get {
                return ResourceManager.GetString("TestCaseFilterFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find a datacollector with friendly name &apos;{0}&apos;..
        /// </summary>
        internal static string UnableToFetchUriString {
            get {
                return ResourceManager.GetString("UnableToFetchUriString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This option works only with vstest.console.exe installed as part of Visual Studio..
        /// </summary>
        internal static string VSInstallationNotFound {
            get {
                return ResourceManager.GetString("VSInstallationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types deriving from the data collection context cannot be used for sending data and messages.  The DataCollectionContext used for sending data and messages must come from one of the events raised to the data collector..
        /// </summary>
        internal static string WrongDataCollectionContextType {
            get {
                return ResourceManager.GetString("WrongDataCollectionContextType", resourceCulture);
            }
        }
    }
}
