//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.TestPlatform.Common.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.TestPlatform.Common.Resources.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving the attributes for the diagnostic data adapter of type &apos;{0}&apos;..
        /// </summary>
        internal static string AttributeRetrievalError {
            get {
                return ResourceManager.GetString("AttributeRetrievalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic data adapter message: {0}.
        /// </summary>
        internal static string DataCollectionMessageFormat {
            get {
                return ResourceManager.GetString("DataCollectionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic data adapter type URI cannot be null or empty. The type URI for the diagnostic data adapter of type &apos;{0}&apos; is null or empty..
        /// </summary>
        internal static string DataCollector_TypeIsNull {
            get {
                return ResourceManager.GetString("DataCollector_TypeIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find diagnostic data adapter &apos;{0}&apos;.  Make sure diagnostic data adapter is installed and try again..
        /// </summary>
        internal static string DataCollectorAssemblyNotFound {
            get {
                return ResourceManager.GetString("DataCollectorAssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic data adapter &apos;{0}&apos; failed to provide intialization information. Error: {1}.
        /// </summary>
        internal static string DataCollectorErrorOnGetVariable {
            get {
                return ResourceManager.GetString("DataCollectorErrorOnGetVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The diagnostic data adapter &apos;{0}&apos;  threw an exception during type loading, construction, or initialization: {1}..
        /// </summary>
        internal static string DataCollectorInitializationError {
            get {
                return ResourceManager.GetString("DataCollectorInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic data adapter (&apos;{0}&apos;) message: {1}..
        /// </summary>
        internal static string DataCollectorMessageFormat {
            get {
                return ResourceManager.GetString("DataCollectorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find diagnostic data adapter of type &apos;{0}&apos; and Uri &apos;{1}&apos;.
        /// </summary>
        internal static string DataCollectorNotFound {
            get {
                return ResourceManager.GetString("DataCollectorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The diagnostic data adapter &apos;{0}&apos; requested environment variable &apos;{1}&apos; with value &apos;{2}&apos; to be set in test execution environment, but another diagnostic data adapter &apos;{3}&apos; has already requested same environment variable with different value &apos;{4}&apos;..
        /// </summary>
        internal static string DataCollectorRequestedDuplicateEnvironmentVariable {
            get {
                return ResourceManager.GetString("DataCollectorRequestedDuplicateEnvironmentVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required diagnostic data adapter attribute &apos;{0}&apos; is missing for the diagnostic data adapter of type &apos;{1}&apos;..
        /// </summary>
        internal static string DataCollectorRequiredAttributeMissing {
            get {
                return ResourceManager.GetString("DataCollectorRequiredAttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get type for diagnostic data adapter &apos;{0}&apos;. Error: {1}..
        /// </summary>
        internal static string DataCollectorTypeNotFound {
            get {
                return ResourceManager.GetString("DataCollectorTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URI format. The URI &apos;{0}&apos; provided for the diagnostic data adapter of type &apos;{1}&apos; is not a valid URI..
        /// </summary>
        internal static string DataCollectorTypeUriFormatInvalid {
            get {
                return ResourceManager.GetString("DataCollectorTypeUriFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending message of Message Type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string DataCollectorUnsupportedMessageType {
            get {
                return ResourceManager.GetString("DataCollectorUnsupportedMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate test extension URI &apos;{0}&apos;.  Ignoring the duplicate extension..
        /// </summary>
        internal static string DuplicateExtensionUri {
            get {
                return ResourceManager.GetString("DuplicateExtensionUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate settings provider named &apos;{0}&apos;.  Ignoring the duplicate provider..
        /// </summary>
        internal static string DuplicateSettingsName {
            get {
                return ResourceManager.GetString("DuplicateSettingsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated run settings section named &apos;{0}&apos; found.  Ignoring the duplicate settings..
        /// </summary>
        internal static string DuplicateSettingsProvided {
            get {
                return ResourceManager.GetString("DuplicateSettingsProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Empty parenthesis ( ).
        /// </summary>
        internal static string EmptyParenthesis {
            get {
                return ResourceManager.GetString("EmptyParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic data adapter friendly names cannot be null or empty. The friendly name for the diagnostic data adapter of type &apos;{0}&apos; is null or empty..
        /// </summary>
        internal static string FriendlyNameIsNullOrEmpty {
            get {
                return ResourceManager.GetString("FriendlyNameIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple configurations that have diagnostic data adapter  type &apos;{0}&apos; or Uri &apos;{1}&apos;. Duplicate configurations will be ignored in the test run..
        /// </summary>
        internal static string IgnoredDuplicateConfiguration {
            get {
                return ResourceManager.GetString("IgnoredDuplicateConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invalid Condition &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidCondition {
            get {
                return ResourceManager.GetString("InvalidCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Extension has an invalid URI &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string InvalidExtensionUriFormat {
            get {
                return ResourceManager.GetString("InvalidExtensionUriFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invalid operator &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidOperator {
            get {
                return ResourceManager.GetString("InvalidOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred while initializing logger with URI &apos;{0}&apos;.  The logger will not be used.  Exception: {1}.
        /// </summary>
        internal static string LoggerInitializationError {
            get {
                return ResourceManager.GetString("LoggerInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a test logger with URI or FriendlyName &apos;{0}&apos;..
        /// </summary>
        internal static string LoggerNotFound {
            get {
                return ResourceManager.GetString("LoggerNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Test Logger URI &apos;{0}&apos; is not valid.  The Test Logger will be ignored..
        /// </summary>
        public static string LoggerUriInvalid
        {
            get
            {
                return ResourceManager.GetString("LoggerUriInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error: Missing &apos;)&apos;.
        /// </summary>
        internal static string MissingCloseParenthesis {
            get {
                return ResourceManager.GetString("MissingCloseParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Missing &apos;(&apos;.
        /// </summary>
        internal static string MissingOpenParenthesis {
            get {
                return ResourceManager.GetString("MissingOpenParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Missing operand.
        /// </summary>
        internal static string MissingOperand {
            get {
                return ResourceManager.GetString("MissingOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Operator &apos;|&apos; or &apos;&amp;&apos;.
        /// </summary>
        internal static string MissingOperator {
            get {
                return ResourceManager.GetString("MissingOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostic data adapter caught an exception of type &apos;{0}&apos;: &apos;{1}&apos;. More details: {2}..
        /// </summary>
        internal static string ReportDataCollectorException {
            get {
                return ResourceManager.GetString("ReportDataCollectorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Run Settings have already been loaded..
        /// </summary>
        internal static string RunSettingsAlreadyLoaded {
            get {
                return ResourceManager.GetString("RunSettingsAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while loading the run settings.  Error: {0}.
        /// </summary>
        internal static string RunSettingsParseError {
            get {
                return ResourceManager.GetString("RunSettingsParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid settings node specified. The name property of the settings node must be non-empty..
        /// </summary>
        internal static string SettingsNodeInvalidName {
            get {
                return ResourceManager.GetString("SettingsNodeInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while initializing the settings provider named &apos;{0}&apos;. Error: {1}.
        /// </summary>
        internal static string SettingsProviderInitializationError {
            get {
                return ResourceManager.GetString("SettingsProviderInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Provider named &apos;{0}&apos; was not found.  The settings can not be loaded..
        /// </summary>
        internal static string SettingsProviderNotFound {
            get {
                return ResourceManager.GetString("SettingsProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect format for TestCaseFilter {0}. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed..
        /// </summary>
        internal static string TestCaseFilterFormatException {
            get {
                return ResourceManager.GetString("TestCaseFilterFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types deriving from the data collection context cannot be used for sending data and messages.  The DataCollectionContext used for sending data and messages must come from one of the events raised to the data collector..
        /// </summary>
        internal static string WrongDataCollectionContextType {
            get {
                return ResourceManager.GetString("WrongDataCollectionContextType", resourceCulture);
            }
        }
    }
}
