//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.TestPlatform.ObjectModel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.TestPlatform.ObjectModel.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-10}  {1}.
        /// </summary>
        internal static string BasicTestResultFormat {
            get {
                return ResourceManager.GetString("BasicTestResultFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The parameter cannot be null or empty..
        /// </summary>
        internal static string Common_CannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("Common_CannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File {0} does not exist..
        /// </summary>
        internal static string Common_FileNotExist {
            get {
                return ResourceManager.GetString("Common_FileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object must be of type {0}..
        /// </summary>
        internal static string Common_ObjectMustBeOfType {
            get {
                return ResourceManager.GetString("Common_ObjectMustBeOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted.
        /// </summary>
        internal static string Common_TestOutcomeAborted {
            get {
                return ResourceManager.GetString("Common_TestOutcomeAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string Common_TestOutcomeCompleted {
            get {
                return ResourceManager.GetString("Common_TestOutcomeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string Common_TestOutcomeDisconnected {
            get {
                return ResourceManager.GetString("Common_TestOutcomeDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Common_TestOutcomeError {
            get {
                return ResourceManager.GetString("Common_TestOutcomeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Common_TestOutcomeFailed {
            get {
                return ResourceManager.GetString("Common_TestOutcomeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inconclusive.
        /// </summary>
        internal static string Common_TestOutcomeInconclusive {
            get {
                return ResourceManager.GetString("Common_TestOutcomeInconclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        internal static string Common_TestOutcomeInProgress {
            get {
                return ResourceManager.GetString("Common_TestOutcomeInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Executed.
        /// </summary>
        internal static string Common_TestOutcomeNotExecuted {
            get {
                return ResourceManager.GetString("Common_TestOutcomeNotExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Runnable.
        /// </summary>
        internal static string Common_TestOutcomeNotRunnable {
            get {
                return ResourceManager.GetString("Common_TestOutcomeNotRunnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        internal static string Common_TestOutcomePassed {
            get {
                return ResourceManager.GetString("Common_TestOutcomePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed (run aborted).
        /// </summary>
        internal static string Common_TestOutcomePassedButRunAborted {
            get {
                return ResourceManager.GetString("Common_TestOutcomePassedButRunAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        internal static string Common_TestOutcomePending {
            get {
                return ResourceManager.GetString("Common_TestOutcomePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string Common_TestOutcomeTimeout {
            get {
                return ResourceManager.GetString("Common_TestOutcomeTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Common_TestOutcomeWarning {
            get {
                return ResourceManager.GetString("Common_TestOutcomeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find TypeConverter for type {0}..
        /// </summary>
        internal static string ConverterNotSupported {
            get {
                return ResourceManager.GetString("ConverterNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find &apos;{0}&apos; node.
        /// </summary>
        internal static string CouldNotFindXmlNode {
            get {
                return ResourceManager.GetString("CouldNotFindXmlNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read from the provided stream.  Data from a stream cannot be sent unless the stream supports reading..
        /// </summary>
        internal static string DataCollectionSink_CanNotReadStream {
            get {
                return ResourceManager.GetString("DataCollectionSink_CanNotReadStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided file name &apos;{0}&apos; contains the following invalid characters: &apos;{1}&apos;..
        /// </summary>
        internal static string DataCollectionSink_InvalidFileNameCharacters {
            get {
                return ResourceManager.GetString("DataCollectionSink_InvalidFileNameCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided file name &apos;{0}&apos; is reserved..
        /// </summary>
        internal static string DataCollectionSink_ReservedFilenameUsed {
            get {
                return ResourceManager.GetString("DataCollectionSink_ReservedFilenameUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot register property &apos;{0}&apos; as value type &apos;{1}&apos; because it was already registered as &apos;{2}&apos;..
        /// </summary>
        internal static string Exception_RegisteredTestPropertyHasDifferentValueType {
            get {
                return ResourceManager.GetString("Exception_RegisteredTestPropertyHasDifferentValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Create msdia Session COM HResult &apos;{0}&apos;..
        /// </summary>
        internal static string FailedToCreateDiaSession {
            get {
                return ResourceManager.GetString("FailedToCreateDiaSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load msdia.
        /// </summary>
        internal static string FailedToLoadMsDia {
            get {
                return ResourceManager.GetString("FailedToLoadMsDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URI in data collector settings &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidDataCollectorUriInSettings {
            get {
                return ResourceManager.GetString("InvalidDataCollectorUriInSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root node of the run settings must be named &apos;RunSettings&apos;..
        /// </summary>
        internal static string InvalidRunSettingsRootNode {
            get {
                return ResourceManager.GetString("InvalidRunSettingsRootNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid settings &apos;{0}&apos;.  Invalid value &apos;{1}&apos; specified for &apos;{2}&apos;..
        /// </summary>
        internal static string InvalidSettingsIncorrectValue {
            get {
                return ResourceManager.GetString("InvalidSettingsIncorrectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid settings &apos;{0}&apos;. Unexpected XmlAttribute: &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidSettingsXmlAttribute {
            get {
                return ResourceManager.GetString("InvalidSettingsXmlAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid settings &apos;{0}&apos;. Unexpected XmlElement: &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidSettingsXmlElement {
            get {
                return ResourceManager.GetString("InvalidSettingsXmlElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URI &apos;{0}&apos; in settings &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidUriInSettings {
            get {
                return ResourceManager.GetString("InvalidUriInSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data collector settings. Expected attribute &apos;{0}&apos; is missing.  A typical data collector setting would look like &lt;DataCollector uri=&quot;dataCollector://Samples/SampleCollector/1.0&quot; assemblyQualifiedName=&quot;Samples.SampleCollector.SampleDataCollector, SampleCollectors, Version=1.0.0.0, Culture=neutral, PublicKeyToken=1111111111111111&quot; friendlyName=&quot;sampleCollector&quot;&gt;..
        /// </summary>
        internal static string MissingDataCollectorAttributes {
            get {
                return ResourceManager.GetString("MissingDataCollectorAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid settings &apos;{0}&apos;. Expected atleast one of the XmlAttribute among friendlyName, uri and assemblyQualifiedName..
        /// </summary>
        internal static string MissingLoggerAttributes {
            get {
                return ResourceManager.GetString("MissingLoggerAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot specify TestCaseFilter for specific tests run. FilterCriteria is only for run with sources..
        /// </summary>
        internal static string NoTestCaseFilterForSpecificTests {
            get {
                return ResourceManager.GetString("NoTestCaseFilterForSpecificTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification frequency need to be a positive value..
        /// </summary>
        internal static string NotificationFrequencyIsNotPositive {
            get {
                return ResourceManager.GetString("NotificationFrequencyIsNotPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification timeout must be greater than zero..
        /// </summary>
        internal static string NotificationTimeoutIsZero {
            get {
                return ResourceManager.GetString("NotificationTimeoutIsZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (null).
        /// </summary>
        internal static string NullString {
            get {
                return ResourceManager.GetString("NullString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution directory &apos;{0}&apos; does not exists. Please make sure solution directory specified in runsettings exists and have read permissions for directory..
        /// </summary>
        internal static string SolutionDirectoryNotExists {
            get {
                return ResourceManager.GetString("SolutionDirectoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter string &apos;{0}&apos; includes unrecognized escape sequence..
        /// </summary>
        internal static string TestCaseFilterEscapeException {
            get {
                return ResourceManager.GetString("TestCaseFilterEscapeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Number.
        /// </summary>
        internal static string TestCasePropertyColumnNumberLabel {
            get {
                return ResourceManager.GetString("TestCasePropertyColumnNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executor Uri.
        /// </summary>
        internal static string TestCasePropertyExecutorUriLabel {
            get {
                return ResourceManager.GetString("TestCasePropertyExecutorUriLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        internal static string TestCasePropertyFilePathLabel {
            get {
                return ResourceManager.GetString("TestCasePropertyFilePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullyQualifiedName.
        /// </summary>
        internal static string TestCasePropertyFullyQualifiedNameLabel {
            get {
                return ResourceManager.GetString("TestCasePropertyFullyQualifiedNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string TestCasePropertyIdLabel {
            get {
                return ResourceManager.GetString("TestCasePropertyIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Number.
        /// </summary>
        internal static string TestCasePropertyLineNumberLabel {
            get {
                return ResourceManager.GetString("TestCasePropertyLineNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TestCasePropertyNameLabel {
            get {
                return ResourceManager.GetString("TestCasePropertyNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string TestCasePropertySourceLabel {
            get {
                return ResourceManager.GetString("TestCasePropertySourceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traits.
        /// </summary>
        internal static string TestCasePropertyTraitsLabel {
            get {
                return ResourceManager.GetString("TestCasePropertyTraitsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Message: {0}.
        /// </summary>
        internal static string TestFailureMessageFormat {
            get {
                return ResourceManager.GetString("TestFailureMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   StackTrace:
        ///{0}.
        /// </summary>
        internal static string TestFailureStackTraceFormat {
            get {
                return ResourceManager.GetString("TestFailureStackTraceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string TestOutcomeFailed {
            get {
                return ResourceManager.GetString("TestOutcomeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string TestOutcomeNone {
            get {
                return ResourceManager.GetString("TestOutcomeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotFound.
        /// </summary>
        internal static string TestOutcomeNotFound {
            get {
                return ResourceManager.GetString("TestOutcomeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        internal static string TestOutcomePassed {
            get {
                return ResourceManager.GetString("TestOutcomePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped.
        /// </summary>
        internal static string TestOutcomeSkipped {
            get {
                return ResourceManager.GetString("TestOutcomeSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0}:
        ///{1}.
        /// </summary>
        internal static string TestResultMessageFormat {
            get {
                return ResourceManager.GetString("TestResultMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Name.
        /// </summary>
        internal static string TestResultPropertyComputerNameLabel {
            get {
                return ResourceManager.GetString("TestResultPropertyComputerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestResult Display Name.
        /// </summary>
        internal static string TestResultPropertyDisplayNameLabel {
            get {
                return ResourceManager.GetString("TestResultPropertyDisplayNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string TestResultPropertyDurationLabel {
            get {
                return ResourceManager.GetString("TestResultPropertyDurationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        internal static string TestResultPropertyEndTimeLabel {
            get {
                return ResourceManager.GetString("TestResultPropertyEndTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Column Number.
        /// </summary>
        internal static string TestResultPropertyErrorColumnNumberLabel {
            get {
                return ResourceManager.GetString("TestResultPropertyErrorColumnNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        internal static string TestResultPropertyErrorMessageLabel {
            get {
                return ResourceManager.GetString("TestResultPropertyErrorMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Stack Trace.
        /// </summary>
        internal static string TestResultPropertyErrorStackTraceLabel {
            get {
                return ResourceManager.GetString("TestResultPropertyErrorStackTraceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome.
        /// </summary>
        internal static string TestResultPropertyOutcomeLabel {
            get {
                return ResourceManager.GetString("TestResultPropertyOutcomeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string TestResultPropertyStartTimeLabel {
            get {
                return ResourceManager.GetString("TestResultPropertyStartTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Test Messages:
        ///{0}.
        /// </summary>
        internal static string TestResultTextMessagesFormat {
            get {
                return ResourceManager.GetString("TestResultTextMessagesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Test Timers:
        ///{0}.
        /// </summary>
        internal static string TestResultTimerMessagesFormat {
            get {
                return ResourceManager.GetString("TestResultTimerMessagesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test property type &apos;{0}&apos; of property &apos;{1}&apos; is not supported. Use one of the supported property type (primitive types, uri, string, string[]) and try again. .
        /// </summary>
        internal static string UnexpectedTypeOfProperty {
            get {
                return ResourceManager.GetString("UnexpectedTypeOfProperty", resourceCulture);
            }
        }
    }
}
