//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.TestPlatform.Common {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.TestPlatform.Common.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Diagnostic data adapter message: {0}.
        /// </summary>
        public static string DataCollectionMessageFormat {
            get {
                return ResourceManager.GetString("DataCollectionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Diagnostic data adapter (&apos;{0}&apos;) message: {1}..
        /// </summary>
        public static string DataCollectorMessageFormat {
            get {
                return ResourceManager.GetString("DataCollectorMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Duplicate test extension URI &apos;{0}&apos;.  Ignoring the duplicate extension..
        /// </summary>
        public static string DuplicateExtensionUri {
            get {
                return ResourceManager.GetString("DuplicateExtensionUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Duplicate settings provider named &apos;{0}&apos;.  Ignoring the duplicate provider..
        /// </summary>
        public static string DuplicateSettingsName {
            get {
                return ResourceManager.GetString("DuplicateSettingsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Duplicated run settings section named &apos;{0}&apos; found.  Ignoring the duplicate settings..
        /// </summary>
        public static string DuplicateSettingsProvided {
            get {
                return ResourceManager.GetString("DuplicateSettingsProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error: Empty parenthesis ( ).
        /// </summary>
        public static string EmptyParenthesis {
            get {
                return ResourceManager.GetString("EmptyParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error: Invalid Condition &apos;{0}&apos;.
        /// </summary>
        public static string InvalidCondition {
            get {
                return ResourceManager.GetString("InvalidCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Test Extension has an invalid URI &apos;{0}&apos;: {1}.
        /// </summary>
        public static string InvalidExtensionUriFormat {
            get {
                return ResourceManager.GetString("InvalidExtensionUriFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error: Invalid operator &apos;{0}&apos;.
        /// </summary>
        public static string InvalidOperator {
            get {
                return ResourceManager.GetString("InvalidOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Exception occurred while initializing logger with URI &apos;{0}&apos;.  The logger will not be used.  Exception: {1}.
        /// </summary>
        public static string LoggerInitializationError {
            get {
                return ResourceManager.GetString("LoggerInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not find a test logger with URI or FriendlyName &apos;{0}&apos;..
        /// </summary>
        public static string LoggerNotFound {
            get {
                return ResourceManager.GetString("LoggerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error: Missing &apos;)&apos;.
        /// </summary>
        public static string MissingCloseParenthesis {
            get {
                return ResourceManager.GetString("MissingCloseParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error: Missing &apos;(&apos;.
        /// </summary>
        public static string MissingOpenParenthesis {
            get {
                return ResourceManager.GetString("MissingOpenParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error: Missing operand.
        /// </summary>
        public static string MissingOperand {
            get {
                return ResourceManager.GetString("MissingOperand", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Missing Operator &apos;|&apos; or &apos;&amp;&apos;.
        /// </summary>
        public static string MissingOperator {
            get {
                return ResourceManager.GetString("MissingOperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The Run Settings have already been loaded..
        /// </summary>
        public static string RunSettingsAlreadyLoaded {
            get {
                return ResourceManager.GetString("RunSettingsAlreadyLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred while loading the run settings.  Error: {0}.
        /// </summary>
        public static string RunSettingsParseError {
            get {
                return ResourceManager.GetString("RunSettingsParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid settings node specified. The name property of the settings node must be non-empty..
        /// </summary>
        public static string SettingsNodeInvalidName {
            get {
                return ResourceManager.GetString("SettingsNodeInvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred while initializing the settings provider named &apos;{0}&apos;. Error: {1}.
        /// </summary>
        public static string SettingsProviderInitializationError {
            get {
                return ResourceManager.GetString("SettingsProviderInitializationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Settings Provider named &apos;{0}&apos; was not found.  The settings can not be loaded..
        /// </summary>
        public static string SettingsProviderNotFound {
            get {
                return ResourceManager.GetString("SettingsProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Incorrect format for TestCaseFilter {0}. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed..
        /// </summary>
        public static string TestCaseFilterFormatException {
            get {
                return ResourceManager.GetString("TestCaseFilterFormatException", resourceCulture);
            }
        }
    }
}
